name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: checkout
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: install
        run: pnpm install
      - name: lint
        run: pnpm run lint
      - name: build
        run: pnpm run build && pnpm run build:monorepo

 