name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: checkout
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install
        run: npm run install --check-files --frozen-lockfile
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build && npm run build:monorepo

 